---
- name: Configure Frontend Server
  hosts: all
  become: true
  tasks:
    - name: Update and upgrade apt packages
      apt:
        update_cache: yes
        upgrade: dist

    - name: Install required packages for Node.js
      apt:
        name:
          - curl
          - gnupg
          - build-essential
          - npm
        state: present

    - name: Download Node.js setup script
      get_url:
        url: https://deb.nodesource.com/setup_20.x
        dest: /tmp/setup_20.x.sh

    - name: Run Node.js setup script
      command: bash /tmp/setup_20.x.sh

    - name: Install Node.js
      apt:
        name: nodejs
        state: present

    - name: Install Angular CLI globally
      command: npm install -g @angular/cli

    - name: Clone repository
      git:
        repo: 'https://github.com/astypczy/ZRCwAW.git'
        dest: /opt/ZRCwAW

    - name: Install frontend dependencies
      command: npm install
      args:
        chdir: /opt/ZRCwAW/ec2/frontend

    - name: Build frontend application
      command: npm run build
      args:
        chdir: /opt/ZRCwAW/ec2/frontend

# sudo ng serve --host 0.0.0.0 --port 4200